# Generated by Django 2.0.7 on 2020-07-05 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200702_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='author',
            field=models.TextField(default='user123', editable=False),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 19, 34, 39, 241806), verbose_name='Date Published'),
        ),
    ]
