# Generated by Django 2.0.7 on 2020-07-05 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200705_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 19, 38, 5, 396530), verbose_name='Date Published'),
        ),
    ]
