# Generated by Django 2.0.7 on 2020-08-28 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200828_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 16, 57, 53, 250378), verbose_name='Date Published'),
        ),
    ]
