# Generated by Django 2.0.7 on 2020-08-29 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200829_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 13, 59, 43, 325983), verbose_name='Date Published'),
        ),
    ]
