# Generated by Django 2.0.7 on 2020-08-29 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200829_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 14, 2, 25, 163434), verbose_name='Date Published'),
        ),
    ]
