# Generated by Django 2.0.7 on 2020-09-01 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200829_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorialseries',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 16, 26, 1, 403663), verbose_name='Date Published'),
        ),
    ]
