# Generated by Django 2.0.7 on 2020-09-01 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200901_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialseries',
            name='category',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 19, 16, 56, 241332), verbose_name='Date Published'),
        ),
        migrations.DeleteModel(
            name='TutorialCategory',
        ),
    ]
