# Generated by Django 2.0.7 on 2020-09-01 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200901_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='series',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 19, 30, 38, 445950), verbose_name='Date Published'),
        ),
    ]
