# Generated by Django 2.0.7 on 2020-09-01 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200901_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 19, 32, 18, 865326), verbose_name='Date Published'),
        ),
    ]
