# Generated by Django 2.0.7 on 2020-09-01 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200901_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='summary',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 19, 36, 14, 387847), verbose_name='Date Published'),
        ),
    ]
