# Generated by Django 2.0.7 on 2020-09-01 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200901_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='author',
            field=models.TextField(default='user123', editable=False),
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 19, 42, 11, 903478), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 19, 42, 11, 903478), verbose_name='Date Published'),
        ),
    ]
