# Generated by Django 2.0.7 on 2020-09-01 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200901_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='title',
            new_name='series',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 19, 45, 55, 361813), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 1, 19, 45, 55, 360814), verbose_name='Date Published'),
        ),
    ]
