# Generated by Django 2.0.7 on 2021-02-03 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200901_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 0, 51, 46, 510631), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='tutorials', to='home.TutorialSeries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 0, 51, 46, 509632), verbose_name='Date Published'),
        ),
    ]
