# Generated by Django 2.0.7 on 2021-03-29 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210321_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 4, 59, 10, 991549), verbose_name='Date Published'),
        ),
    ]
