# Generated by Django 2.0.7 on 2021-04-08 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210408_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.TextField(default='joshuaf319'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.TextField(default='user123'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 11, 4, 37, 72248), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 11, 4, 37, 68252), verbose_name='Date Published'),
        ),
    ]
