# Generated by Django 2.0.7 on 2021-04-10 06:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210408_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('Comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='home.Comment')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 12, 11, 52, 203814), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 12, 11, 52, 190827), verbose_name='Date Published'),
        ),
    ]
