# Generated by Django 2.0.7 on 2021-04-10 06:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210410_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('Comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.Comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='commentchild',
            name='Comment',
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 12, 13, 4, 298595), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 12, 13, 4, 287608), verbose_name='Date Published'),
        ),
        migrations.DeleteModel(
            name='CommentChild',
        ),
    ]
