# Generated by Django 2.0.7 on 2021-04-15 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20210415_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 5, 53, 49, 279078), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 5, 53, 49, 276081), verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 5, 53, 49, 275082), verbose_name='Date Published'),
        ),
    ]
